FROM ubuntu:20.04
ENV LANG C.UTF-8
RUN export TZ=America/New_York
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
    libboost-log-dev \
    libboost-program-options-dev \
    libboost-regex-dev \
    libboost-thread-dev \
    libboost-filesystem-dev \
    cmake \
    g++ \
    python3.8 \
    python3-pip \
 && rm -rf /var/lib/apt/lists/* 
COPY maDGiCart-CH/scripts/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
