name: nvcc11.5.1 arch 3.5/8.0 - Build - CUDA

on: [pull_request, workflow_dispatch]

jobs:
  build-github-runner-and-run:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/11.5.1/local_installers/cuda-repo-ubuntu2004-11-5-local_11.5.1-495.29.05-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2004-11-5-local_11.5.1-495.29.05-1_amd64.deb
          sudo apt-key add /var/cuda-repo-ubuntu2004-11-5-local/7fa2af80.pub
          sudo apt-get update
          sudo apt-get install -y cuda
          sudo apt-get install -y libboost-log-dev libboost-program-options-dev libboost-regex-dev libboost-thread-dev libboost-filesystem-dev
          mkdir build
          cd build
          cmake -DMADG_USE_GPU=On -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.5/bin/nvcc -DCMAKE_CUDA_ARCHITECTURES="35;80" ..
      - name: build
        run: CUDACXX=/usr/local/cuda-11.5/bin/nvcc cmake --build build --target all -j8
      - name: run tests
        run: |
          cd build
          ctest -VV -R unit_testing
