name: Unit testing - Ubuntu 20.04 - GitHub runner

on: [pull_request, workflow_dispatch]

jobs:
  build-github-runner-and-run:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: sudo apt-get install -y libboost-all-dev && mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build --target all -j8
      - name: run tests
        run: |
          cd build
          ctest -VV -R unit_testing
