name: g++9.3.0 - Build & Test - OpenMP

on: [pull_request, workflow_dispatch]

jobs:
  build-github-runner-and-run:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: sudo apt-get install -y libboost-log-dev libboost-program-options-dev libboost-regex-dev libboost-thread-dev libboost-filesystem-dev && mkdir build && cd build && cmake -DMADG_USE_OPENMP=On ..
      - name: build
        run: cmake --build build --target all -j8
      - name: run tests
        run: |
          cd build
          ctest -VV -R unit_testing
