name: Build - CUDA

on: [pull_request, workflow_dispatch]

jobs:
  build-github-runner-and-run:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/11.5.1/local_installers/cuda-repo-ubuntu2004-11-5-local_11.5.1-495.29.05-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2004-11-5-local_11.5.1-495.29.05-1_amd64.deb
          sudo apt-get install -y libboost-log-dev libboost-program-options-dev libboost-regex-dev libboost-thread-dev libboost-filesystem-dev
          mkdir build
          cd build
          cmake -DMADG_USE_OPENMP=On ..
      - name: build
        run: cmake --build build --target all -j8
      - name: run tests
        run: |
          cd build
          ctest -VV -R unit_testing
